### ISSUE TITLE
Lady Proxima + Ma Klounkee - Proxima does not deal damage

### ISSUE THREAD

**Issue by Breich90** [SWU-Karabast/SWUOnline#139]
Ma Klounkee is an Underworld event.  Lady Proxima's `When Played` should trigger when Ma Klounkee specifically bounces Lady Proxima - however, it does not trigger.

**Comment by OotTheMonk** [comment]
If this issue is still occurring, please hit report bug in the menu and include the reference number in the issue ticket. That will let us pull the game state directly into our development environment for debugging, which saves a lot of time.
