### ISSUE TITLE
Sabine Leader is hitting only 3 on the base with Red Three

### ISSUE THREAD

**Issue by brubraz** [SWU-Karabast/SWUOnline#179]
## Expected Behavior
Sabine Leader should deal 4 damage (1 effect damage from Sabine + 2 base damage from Sabine + 1 raid damage from Red Three) to the base along with Red Three.

## Actual Behavior
Only 3 damage is being dealt to the base.

## Steps to Reproduce the Problem

  1. Play Red Three
  2. Attack the base with Sabine Leader
  
  
  I can try to investigate the issue. Could someone point me to the related files?

**Comment by danbastin** [comment]
Might be worth testing Sabine leader without Red Three as well as a normal unit with red three to see if the issue lies with one of the specific cards or if this specific combo is the issue.

**Comment by brubraz** [comment]
In my tests, everything worked perfectly. The confusion may have occurred because the "combat damage" message displayed the value 3. It might be useful to show an exclusive message for the effect damage caused by Sabine.
