### ISSUE TITLE
Fighters for Freedom is not triggering when an event or upgrade is played

### ISSUE THREAD

**Issue by brubraz** [SWU-Karabast/SWUOnline#187]
## Expected Behavior
Fighters for Freedom should deal 1 damage whenever a card with aggression is played.

## Actual Behavior
Fighters for Freedom is not triggering when an event or upgrade is played, only when units are played.

## Steps to Reproduce the Problem
1. Play Fighters for Freedom.
2. Play Heroic Resolve.

**Comment by brubraz** [comment]
After the rule changes, it should deal 1 damage when a red leader is deployed (and played).

**Comment by VJubert** [comment]
@danbastin @OotTheMonk `AllyAbilities.AllyPlayCardAbility` case 5907868016, the first part of if cancels trigger of fighters, I don't know how to fix it today

**Comment by VJubert** [comment]
@brubraz Leaders enter in play and leave it now but you still do not play the card, fighters does not trigger on leaders

**Comment by brubraz** [comment]
@VJubert yes, you are right.

**Comment by OotTheMonk** [comment]
Fixed in e9da86a
