### ISSUE TITLE
Card play timing issues

### ISSUE THREAD

**Issue by danbastin** [SWU-Karabast/SWUOnline#215]
A few issues have been reported with some cards not triggering when they should. These include the following:

725318-0 Krayt still not resolving if it dies with trigger on stack
723931-0 - fighers for freedom did not trigger on multiple occasions
723772-0 maz not getting xp

These may all have a root cause from the recent play timing updates or could be individual cases. Tracking as necessary.

**Comment by danbastin** [comment]
I think a lot of these are simply from ally abilities like this being skipped in a number of scenarios (commonly the played card being an event). 

Relevant code is at NetworkingLibraries.php:1753

**Comment by OotTheMonk** [comment]
Multiple fixes to these cards, and some others: e9da86a and 130dce3

Pulled all three bug reports and no longer able to reproduce after these fixes!
