### ISSUE TITLE
Base was lost during match, replaced by leader when leader deployed as unit.

### ISSUE THREAD

**Issue by tony-pacheco** [SWU-Karabast/SWUOnline#31]
Opponent had used ECL, and deployed Boba Fett leader. Boba Fett leader deployed as unit, but his base was replaced by Boba Fett leader. When attacking, I had only the choice to attack Boba leader and there was no base option. When I attacked Boba Leader, game ended.

Thanks for your hard work!

**Comment by OotTheMonk** [comment]
This was fixed, forgot to close the issue! Was an issue introduced by adding sideboarding.
