### ISSUE TITLE
Energy Conversion Lab -> Guerilla Attack Pod Issue

### ISSUE THREAD

**Issue by kjncl** [SWU-Karabast/SWUOnline#36]
When you ECL the Guerilla Attack Pod. When you trigger the ambush, the when played (if a base has 15 damage) ready this unit does not trigger.

**Comment by OotTheMonk** [comment]
Layer reordering should be working now, can you let us know if this issue recurs? Also hitting report bug in the menu and including the reference number in the issue ticket helps us a lot to reproduce the issue.
