### ISSUE TITLE
Qi'ra Leader Ping With Jango Leader

### ISSUE THREAD

**Issue by charbar486** [SWU-Karabast/SWUOnline#412]
Qi'ra, I Alone Survived: Deal 2 damage to a friendly unit.  Then, give a Shield token to it.

When using this ability the enemy leader Jango Fett, Concealing the Conspiracy, is able to use it's ability to exhaust the ally that Qi'ra shielded.

**Comment by mariotee** [comment]
should be resolved with #422 and #423 
also related: #428 for stuff like OB and Vambrace Flamethrower

**Comment by mariotee** [comment]
should be resolved with https://github.com/SWU-Karabast/SWUOnline/pull/422 and https://github.com/SWU-Karabast/SWUOnline/pull/423
also related: https://github.com/SWU-Karabast/SWUOnline/pull/428 for stuff like OB and Vambrace Flamethrower
