### ISSUE TITLE
Error message popping up after card is played.

### ISSUE THREAD

**Issue by cchambers75** [SWU-Karabast/SWUOnline#66]
I was playing some games today and I played a card on my first turn and an error message popped up on the screen. After this happened, I was unable to attack with that unit. It also did not receive the green border outline showing that it was ready after the resourcing phase ended.

Here is the error message: 

Warning: Array to string conversion in /opt/lampp/htdocs/SWUOnline/Libraries/UILibraries2.php on line 198

**Comment by OotTheMonk** [comment]
Hey, is this still happening? If so, can you hit report bug in the menu and let us know the reference number it gives?
