### ISSUE TITLE
Stack Trace Error in BlockUser.php

### ISSUE THREAD

**Issue by alfonzodesantis** [SWU-Karabast/SWUOnline#68]
When trying to block a user that has already been blocked, a stack trace error is shown based on duplicate entries in the mysql database. We're also disclosed filesystem information within the stack trace.

![trace](https://github.com/SWU-Karabast/SWUOnline/assets/31027383/bdf926f2-4146-4cdf-aebb-c85dfa50d286)

**Comment by danbastin** [comment]
This appears to be working.
