### ISSUE TITLE
Opponent leaves the game

### ISSUE THREAD

**Issue by Orso773** [SWU-Karabast/SWUOnline#79]
When an opponent leaves the game without conceding it is not counted as a victory. In this way the statistics are unrealistic. Is it possible to award victory if an opponent leaves the game?

**Comment by Orso773** [comment]
ok, I see now... if I wait I can claim the victory.

**Comment by doozy1175** [comment]
this isnt always the case. Opponents can often dc without the claim victory option being offered, even after waiting long enough for the lobby to close on its own
