### ISSUE TITLE
Overwhelm applies damage through shields even thought it shouldn't

### ISSUE THREAD

**Issue by adam-b-rokt** [SWU-Karabast/SWUOnline#91]
My opponent had a 6/2 childsen w/ 1 shield and I attacked that unit with a 4/4 K-2SO. I dealt 2 damage to my opponents base via overwhelm when I shouldn't have. I expect my attack to deal 0 damage to the base when I attack a shielded unit.

[Rule 6.3.2.D](https://swudb.com/rules) says the following:
> If the attacker has Overwhelm, deal its excess damage to the opponent’s base, unless the defender had a Shield token that prevented the damage. This excess damage is dealt immediately and is considered combat damage. [See 1.9. Damage](https://swudb.com/rules#1.9)

**Comment by adam-b-rokt** [comment]
I think the issue is at this line: https://github.com/SWU-Karabast/SWUOnline/blob/1620c5fec26a04d4cb9f6a0890bfd567527ef8e5/Libraries/NetworkingLibraries.php#L863

It looks like you would need to check if the defender has a shield before dealing overwhelm damage

**Comment by OotTheMonk** [comment]
Hey, can you try to reproduce this and hit report bug in the menu if it is still occurring? If you hit report bug that lets us pull the game state directly into the development environment with the reference number it gives.
